import type { Job } from "../model/types"

/** Placeholder feed data — realistic enough to design against, replace with API. */
export const JOBS: Job[] = [
  {
    id: "j-1",
    title: "Senior Product Designer",
    salary: "от 300,000 ₽",
    salaryFrom: 300000,
    company: "vc.ru",
    companyInitial: "V",
    logoBg: "#f4e9ff",
    verified: true,
    itAccredited: true,
    online: true,
    location: "Москва",
    experience: "Опыт от 3 до 6 лет",
    experienceFrom: 3,
    experienceTo: 6,
    remoteAllowed: true,
    workMode: "Hybrid",
    type: "Full-time",
    schedule: ["full-day", "flex", "remote"],
    postedAt: "2 часа назад",
    postedHoursAgo: 2,
    description: [
      "Насмотренность. Вы следите за рынком, постоянно отслеживаете обновления интерфейсов популярных UGC-сервисов и легко вспоминаете, где встречали то или иное дизайн-решение.",
      "Структурность. При решении задач вы рассматриваете все возможные варианты. Глубоко прорабатываете каждое решение, чтобы прийти к лучшему. Вы не рисуете макеты, а решаете продуктовые задачи.",
    ],
    tags: ["Figma", "Design Systems", "Prototyping"],
    saved: true,
    detail: {
      rating: 3.8,
      reviewsCount: 32,
      recommendPercent: 78,
      specs: [
        { label: "Требуемый опыт", value: "3–6 лет" },
        { label: "Формат работы", value: "Полная занятость, полный день" },
      ],
      intro:
        "Мы ищем сильного продуктового дизайнера, который любит разбираться в задачах пользователей и доводить интерфейсы до совершенства. Вы будете работать в команде над ключевыми продуктами компании — от исследования до финальной реализации.",
      sections: [
        {
          heading: "Мы предлагаем",
          items: [
            "Работу над продуктом с миллионной аудиторией",
            "Гибкий график и возможность работать удалённо",
            "Прозрачную систему грейдов и роста",
            "Бюджет на обучение, конференции и книги",
          ],
        },
        {
          heading: "Мы ждём кандидата, который умеет",
          items: [
            "Проектировать сложные интерфейсы от гипотезы до решения",
            "Работать с дизайн-системой и поддерживать её консистентность",
            "Аргументировать решения данными и результатами исследований",
            "Плотно сотрудничать с продактами и разработкой",
          ],
        },
        {
          heading: "Условия",
          items: [
            "Оформление по ТК РФ с первого дня",
            "ДМС со стоматологией после испытательного срока",
            "Современный офис в центре и техника на выбор",
          ],
        },
      ],
      skills: [
        "Figma",
        "Design Systems",
        "Prototyping",
        "UX Research",
        "Interaction Design",
        "UI",
      ],
      address: "Москва · Маршала Шевченко, дом 88",
      mapImage:
        "https://images.unsplash.com/photo-1476385822777-70eabacbd41f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      metro: [
        { station: "Полежаевская", color: "#7d2d8f" },
        { station: "Хорошёво", color: "#009e60" },
        { station: "ЦСКА", color: "#f58220" },
      ],
      contactName: "Дмитрий Логинов",
      contactRole: "Дизайн-директор",
      reviews: [
        {
          id: "r-1",
          author: "Анна",
          date: "12 июня 2026",
          rating: 5,
          text: "Отличная команда и адекватные процессы. Дизайн реально влияет на продукт, тебя слышат.",
        },
        {
          id: "r-2",
          author: "Игорь",
          date: "3 мая 2026",
          rating: 4,
          text: "Много интересных задач и рост. Иногда сроки сжатые, но помогают приоритизировать.",
        },
      ],
    },
  },
  {
    id: "j-2",
    title: "Ведущий продуктовый дизайнер в Авто.ру",
    company: "Яндекс",
    companyInitial: "Я",
    logoBg: "#ffe9e3",
    verified: true,
    itAccredited: true,
    online: true,
    location: "Москва",
    matchPercent: 99,
    experience: "Опыт от 3 до 6 лет",
    experienceFrom: 3,
    experienceTo: 6,
    workMode: "On-site",
    type: "Full-time",
    schedule: ["full-day"],
    postedAt: "5 часов назад",
    postedHoursAgo: 5,
    description: [
      "Наблюдательность. Вы следите за рынком, постоянно отслеживаете интерфейсы популярных UGC-сервисов и легко вспоминаете, где встречали удачное решение.",
      "Системный подход. При решении задач вы рассматриваете все возможные варианты и тщательно прорабатываете их, чтобы прийти к одному.",
    ],
    tags: ["Product", "Research", "UI"],
    saved: false,
    detail: {
      rating: 4.4,
      reviewsCount: 128,
      recommendPercent: 89,
      specs: [
        { label: "Требуемый опыт", value: "3–6 лет" },
        { label: "Формат работы", value: "Полная занятость, работа в офисе" },
      ],
      properties: [
        {
          kind: "open",
          label: "Открытая",
          sublabel: "Показывает отзывы сотрудников",
        },
        {
          kind: "rating",
          label: "7 место",
          sublabel: "В Рейтинге работодателей hh.ru",
        },
        {
          kind: "award",
          label: "Победитель",
          sublabel: "Премия HR-бренд",
        },
        {
          kind: "it",
          label: "ИТ-компания",
          sublabel: "Аккредитованный работодатель",
        },
      ],
      intro:
        "Авто.ру ищет ведущего продуктового дизайнера, который возьмёт на себя ключевые пользовательские сценарии сервиса и будет отвечать за качество продукта от исследования до релиза.",
      sections: [
        {
          heading: "Что нужно делать",
          items: [
            "Проектировать сценарии покупки и продажи автомобилей",
            "Проводить и заказывать пользовательские исследования",
            "Развивать дизайн-систему Авто.ру вместе с командой",
            "Защищать решения перед продуктом и бизнесом",
          ],
        },
        {
          heading: "Мы предлагаем",
          items: [
            "Работу над сервисом с десятками миллионов пользователей",
            "Сильную команду дизайнеров и исследователей",
            "ДМС, спорт и корпоративное обучение",
            "Современный офис в Москве рядом с метро",
          ],
        },
      ],
      skills: [
        "Product",
        "Research",
        "UI",
        "Figma",
        "Prototyping",
        "Design Systems",
      ],
      address: "Москва · Льва Толстого, дом 16",
      mapImage:
        "https://images.unsplash.com/photo-1476385822777-70eabacbd41f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      metro: [
        { station: "Парк культуры", color: "#e42313" },
        { station: "Смоленская", color: "#0072bc" },
      ],
      contactName: "Мария Соколова",
      contactRole: "HR-менеджер",
      reviews: [
        {
          id: "r-1",
          author: "Павел",
          date: "20 июля 2026",
          rating: 5,
          text: "Масштаб задач впечатляет, ресурсов на исследования хватает. Дизайн реально влияет на продукт.",
        },
        {
          id: "r-2",
          author: "Ольга",
          date: "14 июня 2026",
          rating: 4,
          text: "Сильная команда и понятные процессы. Иногда много согласований, но это цена масштаба.",
        },
      ],
    },
  },
  {
    id: "j-3",
    title: "Design Engineer",
    salary: "от 250,000 ₽",
    salaryFrom: 250000,
    company: "Stripe",
    companyInitial: "S",
    logoBg: "#e9edff",
    verified: true,
    online: false,
    location: "Санкт-Петербург",
    experience: "Опыт от 2 до 5 лет",
    experienceFrom: 2,
    experienceTo: 5,
    remoteAllowed: true,
    workMode: "Remote",
    type: "Full-time",
    schedule: ["flex", "remote"],
    postedAt: "1 день назад",
    postedHoursAgo: 24,
    description: [
      "Вам важны детали, которые делают интерфейс живым, — анимация, тайминги и мелочи, превращающие продукт в ремесло.",
      "Вы свободно переключаетесь между дизайном и кодом и доводите работу до продакшена.",
    ],
    tags: ["React", "Motion", "CSS"],
    saved: false,
    detail: {
      rating: 4.7,
      reviewsCount: 54,
      recommendPercent: 94,
      specs: [
        { label: "Требуемый опыт", value: "2–5 лет" },
        { label: "Формат работы", value: "Полная занятость, удалённо" },
      ],
      intro:
        "Мы ищем инженера-дизайнера, который живёт на стыке дизайна и кода и умеет доводить интерфейсы до идеального ощущения — с продуманной анимацией и вниманием к деталям.",
      sections: [
        {
          heading: "Обязанности",
          items: [
            "Верстать интерфейсы на React с продуманной анимацией",
            "Поддерживать и развивать библиотеку компонентов",
            "Работать в паре с дизайнерами над деталями взаимодействия",
            "Следить за производительностью и доступностью",
          ],
        },
        {
          heading: "Мы предлагаем",
          items: [
            "Полностью удалённую работу с гибким графиком",
            "Оплату техники и домашнего рабочего места",
            "Культуру ремесла, где важны детали",
            "Конкурентную зарплату в валюте",
          ],
        },
      ],
      skills: [
        "React",
        "TypeScript",
        "Motion",
        "CSS",
        "Accessibility",
        "Design Systems",
      ],
      contactName: "Alex Rivera",
      contactRole: "Engineering Manager",
      reviews: [
        {
          id: "r-1",
          author: "Никита",
          date: "2 августа 2026",
          rating: 5,
          text: "Лучшая инженерная культура, что я видел. Тебе дают время сделать хорошо.",
        },
      ],
    },
  },
  {
    id: "j-4",
    title: "Продакт-менеджер, Growth",
    salary: "от 280,000 ₽",
    salaryFrom: 280000,
    company: "Notion",
    companyInitial: "N",
    logoBg: "#f1f4f9",
    verified: false,
    online: true,
    location: "Удалённо",
    matchPercent: 87,
    experience: "Опыт от 4 до 7 лет",
    experienceFrom: 4,
    experienceTo: 7,
    remoteAllowed: true,
    workMode: "Remote",
    type: "Full-time",
    schedule: ["flex", "remote"],
    postedAt: "1 день назад",
    postedHoursAgo: 26,
    description: [
      "Вы одержимы активацией и удержанием и умеете превращать воронку в набор проверяемых гипотез.",
      "Вы тесно работаете с дизайном и разработкой, чтобы быстро запускать эксперименты и честно читать результаты.",
    ],
    tags: ["Growth", "Analytics", "Experimentation"],
    saved: false,
    detail: {
      rating: 4.2,
      reviewsCount: 41,
      recommendPercent: 85,
      specs: [
        { label: "Требуемый опыт", value: "4–7 лет" },
        { label: "Формат работы", value: "Полная занятость, удалённо" },
      ],
      intro:
        "Мы ищем продакт-менеджера по growth, который превратит воронку активации и удержания в набор проверяемых гипотез и системно ускорит рост продукта.",
      sections: [
        {
          heading: "Что нужно делать",
          items: [
            "Владеть метриками активации и удержания",
            "Формулировать и приоритизировать гипотезы роста",
            "Запускать A/B-эксперименты и честно читать результаты",
            "Работать в связке с дизайном, аналитикой и разработкой",
          ],
        },
        {
          heading: "Мы предлагаем",
          items: [
            "Продукт с международной аудиторией",
            "Полную удалёнку и гибкий график",
            "Свободу в выборе инструментов и подходов",
            "Прозрачную систему целей и бонусов",
          ],
        },
      ],
      skills: [
        "Growth",
        "Analytics",
        "Experimentation",
        "SQL",
        "Product Strategy",
      ],
      contactName: "Emma Chen",
      contactRole: "Head of Growth",
      reviews: [
        {
          id: "r-1",
          author: "Данил",
          date: "9 июля 2026",
          rating: 4,
          text: "Много свободы и ответственности. Если любишь эксперименты — здесь раздолье.",
        },
      ],
    },
  },
  {
    id: "j-5",
    title: "UX/UI дизайнер в финтех-команду",
    salary: "200,000 – 260,000 ₽",
    salaryFrom: 200000,
    company: "Тинькофф",
    companyInitial: "Т",
    logoBg: "#fff3d6",
    verified: true,
    itAccredited: true,
    online: true,
    location: "Москва",
    matchPercent: 91,
    experience: "Опыт от 3 до 6 лет",
    experienceFrom: 3,
    experienceTo: 6,
    remoteAllowed: true,
    workMode: "Hybrid",
    type: "Full-time",
    schedule: ["full-day", "flex"],
    postedAt: "3 часа назад",
    postedHoursAgo: 3,
    description: [
      "Вы проектируете платёжные сценарии, где цена ошибки высока, и умеете держать баланс между скоростью и безопасностью.",
      "Вам близка работа с большими дизайн-системами и метриками — вы измеряете влияние своих решений на конверсию.",
    ],
    tags: ["Figma", "Fintech", "Design Systems"],
    saved: false,
    detail: {
      rating: 4.5,
      reviewsCount: 96,
      recommendPercent: 90,
      specs: [
        { label: "Требуемый опыт", value: "3–6 лет" },
        { label: "Формат работы", value: "Полная занятость, гибрид" },
      ],
      intro:
        "В финтех-команду нужен UX/UI дизайнер, который умеет проектировать платёжные сценарии, где цена ошибки высока, и держит баланс между скоростью, безопасностью и конверсией.",
      sections: [
        {
          heading: "Обязанности",
          items: [
            "Проектировать платёжные и финансовые сценарии",
            "Работать с большой дизайн-системой банка",
            "Измерять влияние решений на конверсию и метрики",
            "Тесно сотрудничать с продуктом и аналитикой",
          ],
        },
        {
          heading: "Мы предлагаем",
          items: [
            "Продукты, которыми пользуются миллионы",
            "Гибрид: офис в центре и удалённые дни",
            "Расширенный ДМС и программы благополучия",
            "Сильную школу дизайна и менторство",
          ],
        },
      ],
      skills: [
        "Figma",
        "Fintech",
        "Design Systems",
        "UX Research",
        "Prototyping",
      ],
      address: "Москва · 2-я Хуторская, дом 38А",
      mapImage:
        "https://images.unsplash.com/photo-1476385822777-70eabacbd41f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      metro: [{ station: "Дмитровская", color: "#909090" }],
      contactName: "Екатерина Волкова",
      contactRole: "Тимлид дизайна",
      reviews: [
        {
          id: "r-1",
          author: "Сергей",
          date: "28 июня 2026",
          rating: 5,
          text: "Зрелые процессы и внимание к деталям. Дизайн здесь по-настоящему ценят.",
        },
        {
          id: "r-2",
          author: "Марина",
          date: "11 мая 2026",
          rating: 4,
          text: "Много ответственности и роста. Нагрузка бывает высокой, но команда поддерживает.",
        },
      ],
    },
  },
  {
    id: "j-6",
    title: "Middle Frontend-разработчик (React)",
    salary: "от 230,000 ₽",
    salaryFrom: 230000,
    company: "Ozon",
    companyInitial: "O",
    logoBg: "#e3f0ff",
    verified: true,
    itAccredited: true,
    online: true,
    location: "Санкт-Петербург",
    experience: "Опыт от 2 до 4 лет",
    experienceFrom: 2,
    experienceTo: 4,
    remoteAllowed: true,
    workMode: "Remote",
    type: "Full-time",
    schedule: ["flex", "remote"],
    postedAt: "6 часов назад",
    postedHoursAgo: 6,
    description: [
      "Вы пишете на TypeScript и React, любите чистый код и переиспользуемые компоненты.",
      "Вам важно, как продукт ощущается пользователем: производительность, доступность и мелкие детали интерфейса.",
    ],
    tags: ["React", "TypeScript", "Next.js"],
    saved: false,
    detail: {
      rating: 4.1,
      reviewsCount: 210,
      recommendPercent: 82,
      specs: [
        { label: "Требуемый опыт", value: "2–4 года" },
        { label: "Формат работы", value: "Полная занятость, удалённо" },
      ],
      intro:
        "Команде Ozon нужен middle frontend-разработчик, который любит чистый код, переиспользуемые компоненты и думает о том, как продукт ощущается пользователем.",
      sections: [
        {
          heading: "Обязанности",
          items: [
            "Разрабатывать интерфейсы на React и TypeScript",
            "Создавать переиспользуемые компоненты и покрывать их тестами",
            "Оптимизировать производительность и доступность",
            "Участвовать в код-ревью и развитии архитектуры",
          ],
        },
        {
          heading: "Мы предлагаем",
          items: [
            "Работу над одним из крупнейших e-com в стране",
            "Удалёнку с возможностью приходить в офис",
            "ДМС, скидки для сотрудников и обучение",
            "Понятную систему грейдов и роста",
          ],
        },
      ],
      skills: [
        "React",
        "TypeScript",
        "Next.js",
        "Jest",
        "Performance",
        "Accessibility",
      ],
      contactName: "Артём Кузнецов",
      contactRole: "IT-рекрутер",
      reviews: [
        {
          id: "r-1",
          author: "Владимир",
          date: "1 августа 2026",
          rating: 4,
          text: "Большой продукт и интересные задачи по нагрузке. Есть чему поучиться у коллег.",
        },
      ],
    },
  },
  {
    id: "j-7",
    title: "Дизайн-лид мобильного направления",
    salary: "от 350,000 ₽",
    salaryFrom: 350000,
    company: "Авито",
    companyInitial: "А",
    logoBg: "#e6fbef",
    verified: true,
    itAccredited: true,
    online: false,
    location: "Москва",
    matchPercent: 82,
    experience: "Опыт от 5 лет",
    experienceFrom: 5,
    workMode: "On-site",
    type: "Full-time",
    schedule: ["full-day"],
    postedAt: "1 день назад",
    postedHoursAgo: 28,
    description: [
      "Вы растите команду дизайнеров, выстраиваете процессы и отвечаете за качество продукта целиком.",
      "Вы умеете переключаться между стратегией и деталями и защищать решения перед бизнесом.",
    ],
    tags: ["Leadership", "Mobile", "Product"],
    saved: false,
    detail: {
      rating: 4.3,
      reviewsCount: 74,
      recommendPercent: 86,
      specs: [
        { label: "Требуемый опыт", value: "от 5 лет" },
        { label: "Формат работы", value: "Полная занятость, работа в офисе" },
      ],
      intro:
        "Авито ищет дизайн-лида мобильного направления, который вырастит команду, выстроит процессы и возьмёт на себя ответственность за качество продукта целиком.",
      sections: [
        {
          heading: "Что нужно делать",
          items: [
            "Растить и развивать команду мобильных дизайнеров",
            "Выстраивать процессы и стандарты качества",
            "Балансировать между стратегией и деталями",
            "Защищать решения перед бизнесом и продуктом",
          ],
        },
        {
          heading: "Мы предлагаем",
          items: [
            "Один из самых посещаемых сервисов рунета",
            "Сильную команду и свободу в построении процессов",
            "ДМС, спорт и корпоративные программы",
            "Просторный офис в Москве",
          ],
        },
      ],
      skills: [
        "Leadership",
        "Mobile",
        "Product",
        "Design Systems",
        "Management",
      ],
      address: "Москва · Лесная, дом 7",
      mapImage:
        "https://images.unsplash.com/photo-1476385822777-70eabacbd41f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      metro: [
        { station: "Белорусская", color: "#009e60" },
        { station: "Новослободская", color: "#8e479c" },
      ],
      contactName: "Игорь Дьяченко",
      contactRole: "Директор по продукту",
      reviews: [
        {
          id: "r-1",
          author: "Юлия",
          date: "17 июля 2026",
          rating: 5,
          text: "Здесь дизайн-лид реально влияет на продукт и команду. Много самостоятельности.",
        },
      ],
    },
  },
  {
    id: "j-8",
    title: "Junior Product Designer",
    salary: "120,000 – 160,000 ₽",
    salaryFrom: 120000,
    company: "Skyeng",
    companyInitial: "S",
    logoBg: "#efeaff",
    verified: false,
    online: true,
    location: "Удалённо",
    experience: "Опыт от 1 года",
    experienceFrom: 1,
    experienceTo: 3,
    remoteAllowed: true,
    workMode: "Remote",
    type: "Full-time",
    schedule: ["flex", "remote"],
    postedAt: "2 дня назад",
    postedHoursAgo: 48,
    description: [
      "Вы делаете первые шаги в продуктовом дизайне и хотите расти рядом с сильными наставниками.",
      "Вы аккуратны в макетах, знаете основы Figma и готовы много учиться на реальных задачах.",
    ],
    tags: ["Figma", "UI", "EdTech"],
    saved: false,
    detail: {
      rating: 4.0,
      reviewsCount: 38,
      recommendPercent: 80,
      specs: [
        { label: "Требуемый опыт", value: "от 1 года" },
        { label: "Формат работы", value: "Полная занятость, удалённо" },
      ],
      intro:
        "Skyeng ищет junior product-дизайнера, который делает первые шаги в профессии и хочет расти рядом с сильными наставниками на реальных продуктовых задачах.",
      sections: [
        {
          heading: "Что нужно делать",
          items: [
            "Работать над интерфейсами образовательных продуктов",
            "Собирать макеты в Figma по гайдам команды",
            "Участвовать в ревью и учиться у старших коллег",
            "Помогать поддерживать дизайн-систему",
          ],
        },
        {
          heading: "Мы предлагаем",
          items: [
            "Наставника и понятный план развития",
            "Полную удалёнку и гибкий график",
            "Доступ к обучающим продуктам компании",
            "Дружелюбную команду без токсичности",
          ],
        },
      ],
      skills: ["Figma", "UI", "EdTech", "Prototyping"],
      contactName: "Анастасия Лебедева",
      contactRole: "HR-специалист",
      reviews: [
        {
          id: "r-1",
          author: "Кирилл",
          date: "5 июля 2026",
          rating: 4,
          text: "Отличное место для старта. Помогают, объясняют, дают расти.",
        },
      ],
    },
  },
  {
    id: "j-9",
    title: "Продуктовый аналитик",
    salary: "от 210,000 ₽",
    salaryFrom: 210000,
    company: "Самокат",
    companyInitial: "С",
    logoBg: "#ffe6f0",
    verified: true,
    itAccredited: true,
    online: true,
    location: "Москва",
    matchPercent: 64,
    experience: "Опыт от 2 до 4 лет",
    experienceFrom: 2,
    experienceTo: 4,
    remoteAllowed: true,
    workMode: "Hybrid",
    type: "Full-time",
    schedule: ["full-day", "flex", "remote"],
    postedAt: "4 часа назад",
    postedHoursAgo: 4,
    description: [
      "Вы превращаете сырые данные в понятные продуктовые выводы и помогаете команде принимать решения.",
      "Вы свободно владеете SQL, умеете строить дашборды и не боитесь A/B-тестов.",
    ],
    tags: ["SQL", "Analytics", "A/B"],
    saved: false,
    detail: {
      rating: 4.4,
      reviewsCount: 63,
      recommendPercent: 88,
      specs: [
        { label: "Требуемый опыт", value: "2–4 года" },
        { label: "Формат работы", value: "Полная занятость, гибрид" },
      ],
      intro:
        "Самокату нужен продуктовый аналитик, который превращает сырые данные в понятные продуктовые выводы и помогает команде принимать решения на основе метрик.",
      sections: [
        {
          heading: "Обязанности",
          items: [
            "Считать и интерпретировать продуктовые метрики",
            "Строить дашборды и автоматизировать отчётность",
            "Дизайнить и анализировать A/B-тесты",
            "Помогать команде формулировать гипотезы",
          ],
        },
        {
          heading: "Мы предлагаем",
          items: [
            "Быстрорастущий продукт с огромным потоком данных",
            "Гибрид и гибкий график",
            "Современный стек аналитики",
            "Команду, которая любит цифры",
          ],
        },
      ],
      skills: ["SQL", "Analytics", "A/B", "Python", "Dashboards"],
      address: "Москва · Садовническая набережная, дом 79",
      mapImage:
        "https://images.unsplash.com/photo-1476385822777-70eabacbd41f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      metro: [{ station: "Павелецкая", color: "#009e60" }],
      contactName: "Роман Фёдоров",
      contactRole: "Руководитель аналитики",
      reviews: [
        {
          id: "r-1",
          author: "Алина",
          date: "22 июля 2026",
          rating: 5,
          text: "Данных много, задачи интересные, команда быстрая. Аналитику здесь слушают.",
        },
      ],
    },
  },

  // The vacancies below exist so every filter option has something to match:
  // internship / project / part-time employment, shift and rotational
  // schedules, and roles open to candidates with no experience. Without them
  // those options silently return an empty feed while their counters promise
  // results. They carry no `detail` — the vacancy view degrades gracefully.
  {
    id: "j-10",
    title: "Стажёр-дизайнер",
    salary: "от 60,000 ₽",
    salaryFrom: 60000,
    company: "Skyeng",
    companyInitial: "S",
    logoBg: "#e8f7ff",
    verified: true,
    itAccredited: true,
    online: true,
    location: "Москва",
    experience: "Без опыта",
    experienceFrom: 0,
    experienceTo: 1,
    remoteAllowed: true,
    workMode: "Hybrid",
    type: "Internship",
    schedule: ["full-day", "flex"],
    postedAt: "5 часов назад",
    postedHoursAgo: 5,
    description: [
      "Стажировка в продуктовой команде: вы работаете с реальными задачами под присмотром наставника.",
      "Мы не ждём опыта в продукте — важнее аккуратность, любопытство и желание разбираться.",
    ],
    tags: ["Figma", "UI"],
    saved: false,
  },
  {
    id: "j-11",
    title: "Дизайнер на проект (лендинги)",
    salary: "от 150,000 ₽",
    salaryFrom: 150000,
    company: "Verta Studio",
    companyInitial: "V",
    logoBg: "#fff3e0",
    verified: false,
    online: true,
    location: "Удалённо",
    matchPercent: 71,
    experience: "Опыт от 2 до 5 лет",
    experienceFrom: 2,
    experienceTo: 5,
    remoteAllowed: true,
    workMode: "Remote",
    type: "Contract",
    schedule: ["flex", "remote"],
    postedAt: "1 день назад",
    postedHoursAgo: 30,
    description: [
      "Проектная работа на серию лендингов для запуска продукта — три месяца с возможностью продления.",
      "Нужен человек, который умеет держать темп и собирать макеты в готовую вёрстку вместе с разработкой.",
    ],
    tags: ["Landing", "Figma", "Webflow"],
    saved: false,
  },
  {
    id: "j-12",
    title: "Оператор поддержки пользователей",
    salary: "от 80,000 ₽",
    salaryFrom: 80000,
    company: "Ozon",
    companyInitial: "O",
    logoBg: "#eef0ff",
    verified: true,
    itAccredited: true,
    online: true,
    location: "Санкт-Петербург",
    experience: "Без опыта",
    experienceFrom: 0,
    experienceTo: 2,
    workMode: "On-site",
    type: "Part-time",
    schedule: ["shift"],
    postedAt: "8 часов назад",
    postedHoursAgo: 8,
    description: [
      "Сменный график 2/2: вы помогаете пользователям в чате и по телефону, разбираете спорные заказы.",
      "Опыт не нужен — учим на месте, важна грамотная речь и спокойствие в разговоре.",
    ],
    tags: ["Support", "CRM"],
    saved: false,
  },
  {
    id: "j-13",
    title: "Инженер дата-центра (вахта)",
    salary: "от 180,000 ₽",
    salaryFrom: 180000,
    company: "Яндекс",
    companyInitial: "Я",
    logoBg: "#fff0e6",
    verified: true,
    itAccredited: true,
    online: false,
    location: "Владимирская область",
    experience: "Опыт от 3 до 6 лет",
    experienceFrom: 3,
    experienceTo: 6,
    workMode: "On-site",
    type: "Full-time",
    schedule: ["rotational"],
    postedAt: "2 дня назад",
    postedHoursAgo: 52,
    description: [
      "Вахтовый метод 15/15 с оплатой проезда и проживания: обслуживание серверного оборудования дата-центра.",
      "Вы работаете руками, читаете схемы и умеете действовать по регламенту в аварийных ситуациях.",
    ],
    tags: ["Hardware", "Linux", "Networking"],
    saved: false,
  },
]
