import type { Appeal } from "../model/types"

export const APPEALS: Appeal[] = [
  {
    id: "a-1",
    company: "PJSC «МТС», Digital",
    companyInitial: "M",
    logoBg: "#ff0032",
    logoColor: "#ffffff",
    position: "Senior Product designer",
    status: "invitation",
    online: true,
    lastMessage: "Здравствуйте, Артём",
    lastTime: "09:06",
    resume: "Senior Product designer",
    quickReplies: [
      "Как до вас доехать?",
      "У меня не получается приехать.",
      "Можем перенести встречу?",
    ],
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "Андрей Васильков",
        title: "Приглашение",
        text: 'Здравствуйте, Иван Федорович! Большое спасибо за интерес, проявленный к вакансии "Бухгалтер". Мы готовы пригласить Вас на дальнейшее интервью по этой вакансии. Отправляю адрес нашего офиса. Будет ли вам удобно приехать 27 октября в 19:00?\n\nС уважением, Андрей Васильков',
        time: "11:02",
      },
      {
        id: "m-2",
        from: "contact",
        text: "Забыл сказать что я завтра выходной",
        time: "12:20",
      },
      {
        id: "m-3",
        from: "me",
        text: "Хорошо, я приду",
        time: "14:18",
        read: true,
      },
      {
        id: "m-4",
        from: "me",
        text: "Только в пятницу можно?",
        time: "14:20",
        read: true,
      },
    ],
  },
  {
    id: "a-2",
    company: "Mayna Labs",
    companyInitial: "M",
    logoBg: "#101828",
    logoColor: "#ffffff",
    position: "Продукт-дизайнер",
    status: "rejected",
    online: true,
    lastMessage: "Здравствуйте, Артём",
    lastTime: "09:06",
    unread: true,
    resume: "Product designer",
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "HR Mayna Labs",
        text: "Здравствуйте, Артём! Спасибо за отклик. К сожалению, сейчас мы не готовы двигаться дальше по этой позиции.",
        time: "09:06",
      },
    ],
  },
  {
    id: "a-3",
    company: "Компания Самолет",
    companyInitial: "С",
    logoBg: "#2f6bff",
    logoColor: "#ffffff",
    position: "Senior UI/UX product designer",
    status: "viewed",
    lastMessage: "Здравствуйте, Артём",
    lastTime: "09:06",
    unread: true,
    resume: "Senior UI/UX product designer",
    messages: [
      {
        id: "m-1",
        from: "me",
        text: "Здравствуйте! Очень заинтересован в вашей вакансии.",
        time: "09:06",
        read: true,
      },
    ],
  },
  {
    id: "a-4",
    company: "Uplab",
    companyInitial: "U",
    logoBg: "#f1f4f9",
    logoColor: "#0d1520",
    position: "Продукт-дизайнер",
    status: "invitation",
    online: true,
    lastMessage: "Здравствуйте, Артём",
    lastTime: "09:06",
    resume: "Product designer",
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "Uplab",
        title: "Приглашение",
        text: "Здравствуйте, Артём! Приглашаем вас на собеседование.",
        time: "09:06",
      },
    ],
  },
  {
    id: "a-5",
    company: "ООО Джем-Софт",
    companyInitial: "Д",
    logoBg: "#ff4d6d",
    logoColor: "#ffffff",
    position: "Продуктовый дизайнер",
    status: "invitation",
    lastMessage: "Здравствуйте! Мои зарплатн…",
    lastTime: "09:06",
    lastRead: true,
    resume: "Product designer",
    messages: [
      {
        id: "m-1",
        from: "me",
        text: "Здравствуйте! Мои зарплатные ожидания — 250 000 ₽.",
        time: "09:06",
        read: true,
      },
    ],
  },
  {
    id: "a-6",
    company: "ООО ФККГруп",
    companyInitial: "Ф",
    logoBg: "#0b3d2e",
    logoColor: "#ffffff",
    position: "Product Designer/ UXUI Designer/ Проду…",
    status: "invitation",
    lastMessage: "Здравствуйте, Артём",
    lastTime: "09:06",
    resume: "Product / UX-UI Designer",
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "ФККГруп",
        title: "Приглашение",
        text: "Здравствуйте, Артём!",
        time: "09:06",
      },
    ],
  },
  {
    id: "a-7",
    company: "Золотое Яблоко",
    companyInitial: "Я",
    logoBg: "#e3ff00",
    logoColor: "#0d1520",
    position: "Senior UX/UI designer",
    status: "invitation",
    lastMessage: "Здравствуйте, Артём",
    lastTime: "09:06",
    resume: "Senior UX/UI designer",
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "Золотое Яблоко",
        title: "Приглашение",
        text: "Здравствуйте, Артём!",
        time: "09:06",
      },
    ],
  },
  {
    id: "a-8",
    company: "Hi, Rockits!",
    companyInitial: "R",
    logoBg: "#101828",
    logoColor: "#ffffff",
    position: "Senior/lead product designer (mobile)",
    status: "invitation",
    lastMessage: "Здравствуйте, Артём",
    lastTime: "09:06",
    resume: "Lead product designer",
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "Rockits",
        title: "Приглашение",
        text: "Здравствуйте, Артём!",
        time: "09:06",
      },
    ],
  },
  {
    id: "a-9",
    company: "билайн: ИТ, Data, Digi…",
    companyInitial: "б",
    logoBg: "#ffd400",
    logoColor: "#0d1520",
    position: "Продукт-дизайнер",
    status: "invitation",
    lastMessage: "Здравствуйте, Артём",
    lastTime: "09:06",
    resume: "Product designer",
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "билайн",
        title: "Приглашение",
        text: "Здравствуйте, Артём!",
        time: "09:06",
      },
    ],
  },
]
