import type { Appeal } from "../model/types"

/** Files in `public/logos`, rooted at Vite's `base`. */
const logo = (file: string) => `${import.meta.env.BASE_URL}logos/${file}`

/** Local wall-clock, `daysBack` calendar days before today. */
function lastSeenAt(daysBack: number, hours: number, minutes: number) {
  const d = new Date()
  d.setDate(d.getDate() - daysBack)
  d.setHours(hours, minutes, 0, 0)
  return d.toISOString()
}

/** Always in the past, so "сегодня" doesn't flip to "только что" before that hour. */
function lastSeenMinutesAgo(minutes: number) {
  return new Date(Date.now() - minutes * 60_000).toISOString()
}

export const APPEALS: Appeal[] = [
  {
    id: "a-1",
    jobId: "j-1",
    company: "PJSC «МТС», Digital",
    companyInitial: "M",
    logoBg: "#ff0032",
    logoColor: "#ffffff",
    position: "Senior Product designer",
    status: "invitation",
    online: true,
    lastSeen: lastSeenMinutesAgo(2),
    lastMessage: "Только в пятницу можно?",
    lastTime: "14:20",
    lastRead: true,
    resume: "Senior Product designer",
    quickReplies: [
      "Как до вас доехать?",
      "У меня не получается приехать.",
      "Можем перенести встречу?",
    ],
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "Андрей Васильков",
        role: "Рекрутер",
        title: "Приглашение",
        text: 'Здравствуйте, Иван Федорович! Большое спасибо за интерес, проявленный к вакансии "Бухгалтер". Мы готовы пригласить Вас на дальнейшее интервью по этой вакансии. Отправляю адрес нашего офиса. Будет ли вам удобно приехать 27 октября в 19:00?\n\nС уважением, Андрей Васильков',
        time: "11:02",
      },
      {
        id: "m-2",
        from: "contact",
        author: "Олег Белов",
        role: "Hiring manager",
        text: "Забыл сказать что я завтра выходной",
        time: "12:20",
      },
      {
        id: "m-3",
        from: "me",
        text: "Хорошо, я приду",
        time: "14:18",
        read: true,
      },
      {
        id: "m-4",
        from: "me",
        text: "Только в пятницу можно?",
        time: "14:20",
        read: true,
      },
    ],
  },
  {
    id: "a-2",
    jobId: "j-2",
    company: "Яндекс",
    companyInitial: "Я",
    logoBg: "#ffe9e3",
    logoUrl: logo("yandex_logo.png"),
    position: "Продукт-дизайнер",
    status: "rejected",
    online: true,
    lastSeen: lastSeenMinutesAgo(1),
    lastMessage: "К сожалению, сейчас мы не готовы",
    lastTime: "18:41",
    unread: true,
    resume: "Product designer",
    messages: [
      {
        id: "m-1",
        from: "me",
        text: "Здравствуйте! Откликаюсь на продукт-дизайнера. В портфолио — B2B-кабинеты и онбординг, ссылка в резюме. Буду рад рассказать подробнее.",
        time: "10:14",
        read: true,
      },
      {
        id: "m-2",
        from: "employer",
        author: "Ольга Смирнова",
        role: "HR BP",
        text: "Артём, добрый день! Спасибо за отклик, резюме сильное. Можем начать с короткого тестового: редизайн карточки тарифа в нашем кабинете. Бриф пришлю сегодня.",
        time: "12:03",
      },
      {
        id: "m-3",
        from: "employer",
        author: "Ольга Смирнова",
        role: "HR BP",
        text: "Бриф в письме и в этом чате: 2–3 экрана, без визуального полиша — важен ход мысли и критерии. Срок — до среды, 18:00.",
        time: "12:08",
      },
      {
        id: "m-4",
        from: "me",
        text: "Принял, спасибо. Отправлю Figma и короткое пояснение к решениям.",
        time: "12:22",
        read: true,
      },
      {
        id: "m-5",
        from: "me",
        text: "Готово: https://figma.com/file/yandex-tariff — доступ по ссылке открыт.",
        time: "17:40",
        read: true,
      },
      {
        id: "m-6",
        from: "employer",
        author: "Ольга Смирнова",
        role: "HR BP",
        text: "Получили, спасибо. Покажем команде и вернёмся.",
        time: "18:05",
      },
      {
        id: "m-7",
        from: "employer",
        author: "Ольга Смирнова",
        role: "HR BP",
        text: "Здравствуйте, Артём! Спасибо за отклик и тестовое — разобрали с дизайнерами. К сожалению, сейчас мы не готовы двигаться дальше по этой позиции: ищем более продуктовый бэкграунд в B2B-биллинге. Резюме оставим в базе, если появится соседняя роль — напишем.",
        time: "18:41",
      },
    ],
  },
  {
    id: "a-3",
    jobId: "j-2",
    company: "Компания Самолет",
    companyInitial: "С",
    logoBg: "#2f6bff",
    logoColor: "#ffffff",
    position: "Senior UI/UX product designer",
    status: "viewed",
    lastSeen: lastSeenAt(1, 18, 3),
    lastMessage: "Резюме посмотрели, отдельного слота",
    lastTime: "11:40",
    unread: true,
    resume: "Senior UI/UX product designer",
    messages: [
      {
        id: "m-1",
        from: "me",
        text: "Здравствуйте! Откликаюсь на Senior UI/UX. Последние годы делал кабинеты для застройщика и ипотечный сценарий — как раз близко к вашему контуру. Портфолио в резюме, если нужно — пришлю 2 кейса отдельно.",
        time: "09:18",
        read: true,
      },
      {
        id: "m-2",
        from: "me",
        text: "Кейсы: подбор квартиры и личный кабинет дольщика. Могу рассказать, как мерили конверсию в бронь.",
        time: "09:21",
        read: true,
      },
      {
        id: "m-3",
        from: "me",
        text: "Добрый день! Подскажите, пожалуйста, посмотрели ли отклик? Если удобнее созвониться на 20 минут — готов на этой неделе.",
        time: "11:04",
        read: true,
      },
      {
        id: "m-4",
        from: "employer",
        author: "Анна",
        role: "HR",
        text: "Артём, здравствуйте. Резюме посмотрели, отдельного слота в команде сейчас нет — если появится, вернёмся. Спасибо, что написали.",
        time: "11:40",
      },
    ],
  },
  {
    id: "a-4",
    jobId: "j-7",
    company: "Авито",
    companyInitial: "А",
    logoBg: "#e6fbef",
    logoUrl: logo("avito_logo.png"),
    position: "Продукт-дизайнер",
    status: "invitation",
    online: true,
    lastSeen: lastSeenMinutesAgo(5),
    lastMessage: "Вам удобно в четверг в 15:00",
    lastTime: "16:05",
    resume: "Product designer",
    quickReplies: [
      "Да, удобно в четверг",
      "Можем созвониться онлайн?",
      "Давайте лучше в пятницу",
    ],
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "Мария Котова",
        role: "Рекрутер",
        title: "Приглашение",
        text: "Здравствуйте, Артём! Спасибо за отклик на продукт-дизайнера. Нам понравились кейсы по лендингам и кабинету — приглашаем на знакомство с командой. Удобно ли встретиться на этой неделе?\n\nС уважением, Мария Котова, HR Авито",
        time: "11:40",
      },
      {
        id: "m-2",
        from: "me",
        text: "Мария, здравствуйте! Спасибо за приглашение, очень интересно. На этой неделе могу в четверг или пятницу после 14:00.",
        time: "12:15",
        read: true,
      },
      {
        id: "m-3",
        from: "employer",
        author: "Мария Котова",
        role: "Рекрутер",
        text: "Отлично. Формат — час в офисе, Бауманская, потом короткий разговор с арт-директором. Нужен ноутбук, тестового заранее не будет.",
        time: "15:51",
      },
      {
        id: "m-4",
        from: "employer",
        author: "Мария Котова",
        role: "Рекрутер",
        text: "Вам удобно в четверг в 15:00 у нас в офисе? Адрес пришлю, как подтвердите.",
        time: "16:05",
      },
    ],
  },
  {
    id: "a-5",
    jobId: "j-3",
    company: "Stripe",
    companyInitial: "S",
    logoBg: "#e9edff",
    logoUrl: logo("stripe_logo.png"),
    position: "Продуктовый дизайнер",
    status: "invitation",
    lastSeen: lastSeenAt(3, 12, 10),
    lastMessage: "Здравствуйте! Мои зарплатные ожидания — 250 000 ₽.",
    lastTime: "12:48",
    lastRead: true,
    resume: "Product designer",
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "Екатерина",
        role: "HR",
        title: "Приглашение",
        text: "Здравствуйте, Артём! Посмотрели резюме на продуктового дизайнера — хотим пригласить на собеседование. Перед созвоном уточним вилку и формат работы, чтобы не тратить время зря.",
        time: "10:02",
      },
      {
        id: "m-2",
        from: "me",
        text: "Екатерина, добрый день! Спасибо, готов созвониться. По формату рассматриваю гибрид, 2–3 дня в офисе.",
        time: "10:36",
        read: true,
      },
      {
        id: "m-3",
        from: "employer",
        author: "Екатерина",
        role: "HR",
        text: "Гибрид как раз наш вариант, офис на Белорусской. Подскажите, пожалуйста, зарплатные ожидания на руки и готовность выйти — чтобы согласовать с руководителем слот.",
        time: "11:19",
      },
      {
        id: "m-4",
        from: "contact",
        author: "Павел",
        role: "Product lead",
        text: "Артём, привет! Я буду на первом созвоне. Интересно, как вы вели дизайн в спринте с разработкой — расскажете на встрече.",
        time: "11:27",
      },
      {
        id: "m-5",
        from: "me",
        text: "Здравствуйте! Мои зарплатные ожидания — 250 000 ₽. Выйти могу через две недели после оффера, с испытательным всё стандартно.",
        time: "12:48",
        read: true,
      },
    ],
  },
  {
    id: "a-6",
    jobId: "j-5",
    company: "Тинькофф",
    companyInitial: "Т",
    logoBg: "#fff3d6",
    logoUrl: logo("tbank_logo.png"),
    position: "Product Designer/ UXUI Designer/ Проду…",
    status: "invitation",
    lastSeen: lastSeenMinutesAgo(180),
    lastMessage: "Ждём макеты до пятницы, 18:00",
    lastTime: "15:22",
    resume: "Product / UX-UI Designer",
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "Игорь Петров",
        role: "Рекрутер",
        title: "Приглашение",
        text: "Здравствуйте, Артём! Приглашаем дальше по вакансии Product / UX-UI Designer. Следующий шаг — короткое тестовое по нашему кабинету клиента, без каверз: смотрим структуру и приоритеты.",
        time: "09:48",
      },
      {
        id: "m-2",
        from: "me",
        text: "Игорь, здравствуйте! Готов взять тестовое. Подскажите объём и срок — сейчас закрываю ещё один кейс, хочу заложить время честно.",
        time: "10:11",
        read: true,
      },
      {
        id: "m-3",
        from: "employer",
        author: "Игорь Петров",
        role: "Рекрутер",
        text: "Один пользовательский сценарий: заявка на лимит + статус в кабинете. 3–4 экрана, можно вайрфреймы. Срок — 4 рабочих дня. Оплата тестового — 15 000 ₽, если дойдём до него.",
        time: "11:05",
      },
      {
        id: "m-4",
        from: "me",
        text: "Объём понятный, спасибо. Бриф и доступы к референсам можно сюда?",
        time: "11:18",
        read: true,
      },
      {
        id: "m-5",
        from: "employer",
        author: "Игорь Петров",
        role: "Рекрутер",
        text: "Файл с брифом отправил на почту из резюме, дублирую ссылку: диск / Тинькофф-тест-Артём. Если что-то не открывается — напишите.",
        time: "14:40",
      },
      {
        id: "m-6",
        from: "employer",
        author: "Игорь Петров",
        role: "Рекрутер",
        text: "Ждём макеты до пятницы, 18:00. После разбора пригласим на встречу с руководителем продукта.",
        time: "15:22",
      },
    ],
  },
  {
    id: "a-7",
    jobId: "j-7",
    company: "Золотое Яблоко",
    companyInitial: "Я",
    logoBg: "#e3ff00",
    logoColor: "#0d1520",
    position: "Senior UX/UI designer",
    status: "invitation",
    lastSeen: lastSeenAt(5, 19, 12),
    lastMessage: "Тогда до четверга, в 11:00 пришлю",
    lastTime: "11:37",
    resume: "Senior UX/UI designer",
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "Дарья",
        role: "Talent Acquisition",
        title: "Приглашение",
        text: "Здравствуйте, Артём! Приглашаем на интервью по Senior UX/UI — e-com витрина и приложение. Команде откликнулись кейсы с каталогом и чекаутом.",
        time: "09:20",
      },
      {
        id: "m-2",
        from: "me",
        text: "Дарья, здравствуйте! Спасибо, направление очень близкое. Удобнее созвон или офис?",
        time: "09:44",
        read: true,
      },
      {
        id: "m-3",
        from: "employer",
        author: "Дарья",
        role: "Talent Acquisition",
        text: "Первый шаг — 45 минут в Zoom с дизайн-лидом, потом при желании офис. Четверг утром или пятница после 16:00?",
        time: "10:08",
      },
      {
        id: "m-4",
        from: "me",
        text: "Четверг утром лучше, с 11:00 буду свободен.",
        time: "10:21",
        read: true,
      },
      {
        id: "m-5",
        from: "contact",
        author: "Лена",
        role: "Design lead",
        text: "Артём, привет! Я подключусь в четверг. Посмотрим один кейс глубоко — лучше каталог или чекаут, как вам комфортнее.",
        time: "10:55",
      },
      {
        id: "m-6",
        from: "employer",
        author: "Дарья",
        role: "Talent Acquisition",
        text: "Тогда до четверга, в 11:00 пришлю ссылку на Zoom и короткий гайд, что взять с собой.",
        time: "11:37",
      },
    ],
  },
  {
    id: "a-8",
    jobId: "j-8",
    company: "Skyeng",
    companyInitial: "S",
    logoBg: "#efeaff",
    logoUrl: logo("skyeng_logo.png"),
    position: "Senior/lead product designer (mobile)",
    status: "invitation",
    lastSeen: lastSeenAt(40, 12, 0),
    lastMessage: "Следующий шаг — созвон с CPO",
    lastTime: "17:50",
    resume: "Lead product designer",
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "Катя",
        role: "People partner",
        title: "Приглашение",
        text: "Здравствуйте, Артём! Ищем senior/lead product designer в мобайл. По резюме видно сильный продуктовый след — приглашаем поговорить. Есть 20–30 минут на этой неделе?",
        time: "13:10",
      },
      {
        id: "m-2",
        from: "me",
        text: "Катя, здравствуйте! Есть, спасибо. Могу завтра после 16:00 или в среду утром. Если нужно — сразу пришлю 2 мобильных кейса.",
        time: "13:28",
        read: true,
      },
      {
        id: "m-3",
        from: "me",
        text: "Кейсы: онбординг финтеха и главный экран с персональными сценариями. Оба — iOS, команда 4–6 человек.",
        time: "13:30",
        read: true,
      },
      {
        id: "m-4",
        from: "employer",
        author: "Катя",
        role: "People partner",
        text: "Кейсы посмотрели, спасибо. На лиде нам важно, как вы растили младших и спорили с продуктом за scope. Расскажете на созвоне?",
        time: "16:12",
      },
      {
        id: "m-5",
        from: "me",
        text: "Да, это как раз про последний год: менторил двух middle, вёл дизайн-криты и приоритизацию с PO. Готов подробнее.",
        time: "16:40",
        read: true,
      },
      {
        id: "m-6",
        from: "employer",
        author: "Катя",
        role: "People partner",
        text: "Следующий шаг — созвон с CPO, час, онлайн. Слот пришлю завтра утром — ориентир среда 11:00.",
        time: "17:50",
      },
    ],
  },
  {
    id: "a-9",
    jobId: "j-9",
    company: "билайн: ИТ, Data, Digi…",
    companyInitial: "б",
    logoBg: "#ffd400",
    logoColor: "#0d1520",
    position: "Продукт-дизайнер",
    status: "invitation",
    lastSeen: lastSeenAt(2, 9, 45),
    lastMessage: "Четверг в 12:00 подходит, буду",
    lastTime: "13:14",
    lastRead: true,
    resume: "Product designer",
    messages: [
      {
        id: "m-1",
        from: "employer",
        author: "Наталья Волкова",
        role: "HR BP",
        title: "Приглашение",
        text: "Здравствуйте, Артём! Приглашаем на интервью по продукт-дизайнеру в Digital. Первая встреча — с HR и дизайн-лидом, около часа. Вам удобнее офис на Преображенке или онлайн?",
        time: "09:55",
      },
      {
        id: "m-2",
        from: "me",
        text: "Наталья, здравствуйте! Спасибо за приглашение. На этой неделе удобнее онлайн — если можно Teams или Zoom.",
        time: "10:20",
        read: true,
      },
      {
        id: "m-3",
        from: "employer",
        author: "Наталья Волкова",
        role: "HR BP",
        text: "Онлайн ок, будет Teams. Среда 16:00 или четверг 12:00 — что ближе?",
        time: "11:02",
      },
      {
        id: "m-4",
        from: "me",
        text: "Среду, к сожалению, уже занял. Четверг в 12:00 свободен.",
        time: "11:18",
        read: true,
      },
      {
        id: "m-5",
        from: "employer",
        author: "Наталья Волкова",
        role: "HR BP",
        text: "Фиксирую четверг, 12:00. Календарь и ссылку на Teams пришлю до конца дня. Если перенесётся с нашей стороны — напишу сюда.",
        time: "12:41",
      },
      {
        id: "m-6",
        from: "me",
        text: "Четверг в 12:00 подходит, буду. Если нужно что-то подготовить заранее — напишите.",
        time: "13:14",
        read: true,
      },
    ],
  },
]
